<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
 
    <xacro:include filename="robot_properties.xacro"/>
 
    <gazebo reference="wheel_fr_link">
        <material>Gazebo/Orange</material>
    </gazebo>
 
    <gazebo reference="wheel_fl_link">
        <material>Gazebo/Orange</material>
    </gazebo>
 
    <gazebo reference="wheel_br_link">
        <material>Gazebo/Orange</material>
    </gazebo>
 
    <gazebo reference="wheel_bl_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="servo_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo>
        <plugin name="servo" filename="libservo_plugin.so">
            <joint>servo_joint</joint>
            <topic>/cmd_servo</topic>
            <parent_link>actuator_link</parent_link>
            <child_link>servo_link</child_link>
        </plugin>
    </gazebo>
 
    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            <!-- Wheel info -->
            <num_wheel_pairs>2</num_wheel_pairs>
            <left_joint>wheel_fl_joint</left_joint>
            <left_joint>wheel_bl_joint</left_joint>
 
            <right_joint>wheel_fr_joint</right_joint>
            <right_joint>wheel_br_joint</right_joint>
 
            <wheel_separation>${base_width}</wheel_separation>
            <wheel_separation>${base_width}</wheel_separation>
 
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
 
 
            <!-- Limits -->
            <max_wheel_torque>10000</max_wheel_torque>
            <max_wheel_acceleration>4.0</max_wheel_acceleration>
 
            <!-- Output -->
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
 
            <publish_odom>true</publish_odom>
            <publish_odom_tf>false</publish_odom_tf>
            <publish_wheel_tf>false</publish_wheel_tf>
        </plugin>
    </gazebo>
</robot>