<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
 
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
 
    <material name="grey">
        <color rgba="0.8 0.8 0.8 1"/>
    </material>
 
    <material name="blue">
        <color rgba="0.3 1.0 0.3 1"/>
    </material>
 
    <xacro:include filename="robot_properties.xacro" />
    <xacro:include filename="robot_wheel.xacro" />
    <xacro:include filename="robot_inertia.xacro" />
  
    <link name="base_link">
        <!-- Base -->
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="grey" />
        </visual>
        <!-- Conveyor belt -->
        <visual>
            <origin xyz="${base_length*0.2} 0 ${base_height*1.15}" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height*0.9}" />
            </geometry>
        </visual>
        <!-- Ebox -->
        <visual>
            <origin xyz="${base_length*0.6} 0 ${base_height*2.05 + 0.09}" />
            <geometry>
                <box size="0.165 ${base_width} 0.178" />
            </geometry>
        </visual>

        <!--
        <visual>
            <origin xyz="-0.3 0 ${base_height*2}" rpy="0 -0.4135 0"/>
            <geometry>
                <box size="0.9 ${base_width*0.9} 0.162" />
            </geometry>
        </visual>-->
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </link>
 
    <xacro:include filename="robot_actuator.xacro"   />
    <!-- xacro:include filename="robot_imu.xacro"       / -->
    <xacro:include filename="robot_depth.xacro"     />
    <xacro:include filename="robot_gazebo.xacro" />


    <xacro:wheel name="fr" x="${base_length / 2 - 0.1}" y="${base_width / 2}" wheel_offset="${wheel_thickness / 2}"/>
    <xacro:wheel name="fl" x="${base_length / 2 - 0.1}" y="${-base_width / 2}" wheel_offset="${-wheel_thickness / 2}"/>
    <xacro:wheel name="br" x="${-base_length / 2 + 0.1}" y="${base_width / 2}" wheel_offset="${wheel_thickness / 2}"/>
    <xacro:wheel name="bl" x="${-base_length / 2 + 0.1}" y="${-base_width / 2}" wheel_offset="${-wheel_thickness / 2}"/>
 
 
 
</robot>